import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const rightPanel = fs.readFileSync(new URL("./RightPanel.tsx", import.meta.url), "utf8");
const review = fs.readFileSync(new URL("./ReviewPanel.tsx", import.meta.url), "utf8");
const changeList = fs.readFileSync(new URL("./ChangeList.tsx", import.meta.url), "utf8");
const shell = fs.readFileSync(new URL("../AppShell.tsx", import.meta.url), "utf8");
const sidebar = fs.readFileSync(new URL("../SessionSidebar.tsx", import.meta.url), "utf8");

test("moves files and review into a Codex-style launcher and tool-tab workspace", () => {
  assert.match(rightPanel, /role="tablist"/);
  assert.match(rightPanel, /role="tab"/);
  assert.match(rightPanel, /role="tabpanel"/);
  assert.match(rightPanel, /className=\{styles\.toolLauncher\}/);
  assert.match(rightPanel, /className=\{styles\.toolMenu\} role="menu"/);
  assert.match(rightPanel, /const \[openTools, setOpenTools\]/);
  assert.match(rightPanel, /current\.includes\(tab\) \? current : \[\.\.\.current, tab\]/);
  assert.match(rightPanel, /openTools\.map/);
  assert.match(rightPanel, /draggable/);
  assert.match(rightPanel, /text\/piora-tool-tab/);
  assert.match(rightPanel, /moveTool\(source, tool\.id\)/);
  assert.match(rightPanel, /createPortal/);
  assert.match(rightPanel, /window\.innerWidth - width - inset/);
  assert.match(rightPanel, /closeTool\(tool\.id\)/);
  assert.match(rightPanel, /event\.key === "ArrowRight"/);
  assert.match(rightPanel, /onMaximizedChange/);
  assert.match(rightPanel, /<FileExplorer/);
  assert.match(rightPanel, /<FileViewer/);
  assert.match(rightPanel, /<CommandPanel/);
  assert.match(rightPanel, /<BrowserPanel/);
  assert.match(rightPanel, /<SafeHarmonyPanel/);
  assert.match(rightPanel, /<DesignToHarmonyPanel/);
  assert.match(rightPanel, /sessionRunning=\{props\.sessionRunning\}/);
  assert.match(rightPanel, /onGuideAgent=\{props\.onGuideAgent\}/);
  assert.match(rightPanel, /sessionTools\.panelDeviceUnavailable/);
  assert.doesNotMatch(rightPanel, /<SearchPanel/);
  assert.match(rightPanel, /id: "review"/);
  assert.match(rightPanel, /id: "commands"/);
  assert.match(rightPanel, /id: "browser"/);
  assert.match(rightPanel, /id: "design"/);
  assert.match(rightPanel, /id: "harmony"/);
  assert.match(rightPanel, /id: "files"/);
  assert.doesNotMatch(rightPanel, /workspace-search/);
  assert.match(shell, /piora-right-panel-tab/);
  assert.match(shell, /useState<RightPanelTab>\("home"\)/);
  assert.match(shell, /rightPanelMaximized/);
  assert.match(shell, /rightPanelTabRestored/);
  assert.doesNotMatch(shell, /useState<RightPanelTab>\(\(\) =>/);
  assert.doesNotMatch(sidebar, /<FileExplorer|<SidebarFileArea/);
});

test("the command panel owns a persistent workspace shell while file lookup stays in Files", () => {
  const commandPanel = fs.readFileSync(new URL("./CommandPanel.tsx", import.meta.url), "utf8");
  const terminal = fs.readFileSync(new URL("./TerminalSurface.tsx", import.meta.url), "utf8");
  assert.match(commandPanel, /useAgentTerminal\(sessionId\)/);
  assert.match(commandPanel, /<TerminalSurface/);
  assert.match(commandPanel, /role="tablist"/);
  assert.match(commandPanel, /agent\.commands/);
  assert.match(terminal, /\/api\/terminal\/events/);
  assert.match(commandPanel, /\/api\/terminal/);
  assert.match(terminal, /new EventSource/);
  assert.match(terminal, /action: "start"/);
  assert.match(terminal, /action: "input", data/);
  assert.doesNotMatch(commandPanel, /controls\.runCommand|excludeFromContext/);
  assert.match(shell, /navigate\.searchFiles[\s\S]*?setRightPanelTab\("files"\)/);
  assert.match(shell, /focusFileSearch/);
});

test("the browser panel matches its Chromium viewport and forwards native pointer phases", () => {
  const browser = fs.readFileSync(new URL("./BrowserPanel.tsx", import.meta.url), "utf8");
  assert.match(browser, /new ResizeObserver/);
  assert.match(browser, /createBrowserViewportSync/);
  assert.match(browser, /bridge\.setViewport/);
  assert.match(browser, /transitionend/);
  assert.match(browser, /\[[^\]]*maximized[^\]]*syncViewport[^\]]*\]/);
  assert.match(browser, /action: "resize"/);
  assert.match(browser, /onPointerMove/);
  assert.match(browser, /action: "mouse_down"/);
  assert.match(browser, /action: "mouse_up"/);
  assert.match(browser, /setPointerCapture/);
  assert.match(browser, /state\?\.cursor/);
});

test("review groups changes, supports keyboard navigation, diff rendering, and safe mutations", () => {
  assert.match(review, /createItems/);
  assert.match(review, /group: "staged"/);
  assert.match(review, /group: "unstaged"/);
  assert.match(review, /group: "untracked"/);
  assert.match(changeList, /event\.altKey/);
  assert.match(review, /<DiffView/);
  assert.doesNotMatch(review, /reviewOverview|FileIndexRow|loadMoreFiles/);
  assert.match(review, /`\/api\/git\/\$\{action\}`/);
  assert.match(review, /"\/api\/git\/commit"/);
  assert.match(review, /"\/api\/git\/push"/);
  assert.match(review, /includeUnstaged/);
  assert.match(review, /review\.commitAndPush/);
  assert.match(review, /context=all/);
  assert.doesNotMatch(review, /className=\{styles\.fileCollapse\}/);
  assert.match(review, /className=\{styles\.fileGroupBadge\}/);
  assert.match(review, /name="external-link"/);
  assert.match(review, /requestConfirmation/);
  assert.doesNotMatch(review, /window\.confirm/);
  assert.match(review, /"\/api\/git\/branches"/);
  assert.match(review, /className=\{styles\.branchMenu\}/);
  assert.match(review, /className=\{styles\.reviewLoading\}/);
  assert.match(review, /piora:git-status-changed/);
});
