import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { chromium } from "playwright-core";
import { buildClipboardUI, clipboardTheme } from "./clipboard-ui-fixture.mjs";

import { setup } from "./clipboard-test-data.mjs";

test("v2 uses paste semantics, preserves ordered cross-filter selection, protects browse position and drafts", { timeout: 120000 }, async () => {
  const directory = await mkdtemp(path.join(tmpdir(), "piora-clipboard-v2-ui-"));
  let browser;
  try {
    const { bundle, css } = await buildClipboardUI(directory);
    const samplePNG = await readFile(path.resolve("docs/design/clipboard/manager-v3.png"));
    browser = await chromium.launch({ channel: "msedge", headless: true });
    const context = await browser.newContext({ viewport: { width: 1100, height: 900 } });
    const page = await context.newPage();
    const errors = [], remote = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("request", request => { if (request.url().includes("remote.invalid")) remote.push(request.url()); });
    await page.context().route("https://clipboard-v2.test/**", route => route.fulfill(route.request().url().endsWith("sample.png") ? { contentType: "image/png", body: samplePNG } : route.request().url().endsWith("bundle.js") ? { contentType: "text/javascript", body: bundle } : { contentType: "text/html", body: `<!doctype html><meta charset="utf-8"><style>${clipboardTheme}${css}</style><div id="root"></div><script>${setup}</script><script src="/bundle.js"></script>` }));
    await page.goto("https://clipboard-v2.test/");
    await page.getByRole("listbox").getByRole("option").first().waitFor();
    await page.evaluate(() => { window.storageState = 'failed'; window.emit('status'); });
    await page.getByText('历史暂不可用', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: /^粘贴/ }).isDisabled(), true);
    assert.equal(await page.getByRole('button', { name: '复制', exact: true }).isDisabled(), true);
    await mkdir(path.resolve('.verification/clipboard-v3'), { recursive: true });
    await page.screenshot({ path: path.resolve('.verification/clipboard-v3/storage-disconnected.png') });
    await page.getByRole('button', { name: '重新连接存储', exact: true }).click();
    await page.getByText('已重新连接。未确认的操作未重放，请核对最近记录。', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '复制', exact: true }).isDisabled(), false);
    await page.getByLabel('内容信息').getByText('9 字符 · 1 行', { exact: true }).waitFor();
    await page.getByRole('listbox').getByRole('option').filter({ hasText: '设计参考' }).click();
    assert.equal(await page.evaluate(() => window.commands.some(command => command.type === 'open-link')), false, 'previewing a link does not navigate');
    await page.getByRole('button', { name: '在浏览器打开 example.com', exact: true }).click();
    await page.waitForFunction(() => window.commands.some(command => command.type === 'open-link' && command.id === 'row-1'));
    assert.ok(await page.getByRole("listbox").getByRole("option").count() < 35, "list mounts only visible rows");
    await page.getByLabel("搜索剪贴板").fill("产品说明");
    await page.waitForFunction(() => document.querySelectorAll('[role="option"]').length === 1);
    await page.getByLabel("搜索剪贴板").press("Shift+Enter");
    await page.waitForFunction(() => window.commands.some(c => c.type === 'paste' && c.plain && c.ids[0] === 'row-0'));
    await page.getByLabel("搜索剪贴板").fill("");
    await page.getByRole("listbox").getByRole("option").filter({ hasText: "设计参考" }).hover();
    await page.getByLabel("选择 设计参考", { exact: true }).check();
    await page.getByLabel("选择 产品说明", { exact: true }).check();
    await page.getByRole("navigation", { name: "内容类型" }).getByRole("button", { name: "收藏", exact: true }).click();
    await page.getByText("已选 2 条", { exact: true }).waitFor();
    await page.getByLabel("合并分隔符").selectOption(", ");
    await page.getByRole("button", { name: "合并复制", exact: true }).click();
    await page.waitForFunction(() => window.commands.some(c => c.type === 'copy'));
    assert.deepEqual(await page.evaluate(() => window.commands.findLast(c => c.type === 'copy').ids), ["row-1", "row-0"]);
    await page.getByLabel("合并分隔符").selectOption("custom");
    await page.getByLabel("自定义分隔符").fill(" · ");
    await page.getByRole("button", { name: "合并预览", exact: true }).click();
    await page.getByRole("dialog", { name: "合并预览", exact: true }).waitFor();
    assert.equal(await page.getByRole("dialog").locator("pre").textContent(), "https://example.com/design · 复制后可以直接粘贴");
    await page.getByRole("dialog").getByRole("button", { name: "复制", exact: true }).click();
    await page.waitForFunction(() => window.commands.findLast(c => c.type === 'copy')?.separator === ' · ');
    await page.getByRole("button", { name: "关闭", exact: true }).click();
    await page.getByRole("button", { name: "取消选择", exact: true }).click();
    await page.getByRole("button", { name: "全部", exact: true }).click();
    await page.getByRole("listbox").getByRole("option").filter({ hasText: "产品说明" }).click();
    await page.getByRole("button", { name: "查看格式", exact: true }).click();
    await page.frameLocator('iframe[title="富文本预览"]').getByText("正文", { exact: false }).waitFor();
    assert.deepEqual(remote, [], "rich previews never request remote assets");
    assert.equal(await page.evaluate(() => window.compromised), undefined);
    await page.evaluate(() => { const entry = window.entries.find(e => e.id === 'row-0'); window.originalHTML = entry.html; entry.html = '<div>' + '<span>长文</span>'.repeat(25000) + '</div>'; window.emit('mutation'); });
    await page.frameLocator('iframe[title="富文本预览"]').getByText('内容较长，已缩短预览；复制或粘贴仍使用完整原格式。', { exact: true }).waitFor();
    assert.ok(await page.frameLocator('iframe[title="富文本预览"]').locator('body *').count() <= 10002, 'rich preview DOM stays bounded');
    assert.ok(await page.evaluate(() => window.entries.find(e => e.id === 'row-0').html.length) > 256000, 'preview truncation does not alter the saved representation');
    await page.evaluate(() => { window.entries.find(e => e.id === 'row-0').html = window.originalHTML; window.emit('mutation'); });
    await page.getByLabel("剪贴板备注").fill("未保存的备注");
    await page.evaluate(() => { window.fail = true; });
    await page.getByRole("button", { name: "保存备注", exact: true }).click();
    await page.getByRole("alert").filter({ hasText: "磁盘写入失败" }).waitFor();
    assert.equal(await page.getByLabel("剪贴板备注").inputValue(), "未保存的备注");
    await page.evaluate(() => { window.fail = false; });
    await page.getByRole("button", { name: "保存备注", exact: true }).click();
    await page.waitForFunction(() => window.entries[0].remark === '未保存的备注');
    // A failed save must leave both the pending navigation and the draft intact.
    await page.getByLabel("剪贴板备注").fill("离开前保存的备注");
    await page.getByRole("listbox").getByRole("option").filter({ hasText: "设计参考" }).click();
    const draftDialog = page.getByRole("dialog", { name: "保留未保存的编辑" });
    await draftDialog.waitFor();
    await mkdir(path.resolve('.verification/clipboard-v3'), { recursive: true });
    await page.screenshot({ path: path.resolve('.verification/clipboard-v3/unsaved-edits.png') });
    await draftDialog.getByRole("button", { name: "继续编辑", exact: true }).click();
    assert.equal(await page.getByLabel("剪贴板备注").inputValue(), "离开前保存的备注");
    await page.getByRole("listbox").getByRole("option").filter({ hasText: "设计参考" }).click();
    await page.evaluate(() => { window.fail = true; });
    await draftDialog.getByRole("button", { name: "保存并继续", exact: true }).click();
    await draftDialog.getByRole("alert").filter({ hasText: "磁盘写入失败" }).waitFor();
    assert.equal(await page.getByLabel("剪贴板备注").inputValue(), "离开前保存的备注");
    await page.evaluate(() => { window.fail = false; });
    await draftDialog.getByRole("button", { name: "保存并继续", exact: true }).click();
    await page.waitForFunction(() => document.querySelector('article header strong')?.textContent === '设计参考');
    assert.equal(await page.evaluate(() => window.entries.find(e => e.id === 'row-0').remark), "离开前保存的备注");
    await page.getByLabel("剪贴板备注").fill("不要保留");
    await page.getByRole("button", { name: "全部", exact: true }).click();
    await draftDialog.getByRole("button", { name: "放弃修改并继续", exact: true }).click();
    await page.waitForFunction(() => document.querySelector('article header strong')?.textContent === '产品说明');
    assert.equal(await page.evaluate(() => window.entries.find(e => e.id === 'row-1').remark), "");
    await page.getByRole("button", { name: "剪贴板更多操作", exact: true }).click();
    await page.getByRole("button", { name: "导出历史…", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "已导出历史、格式、图片和暂存记录。" }).waitFor();
    await page.evaluate(() => { window.importResult = { imported: 2, merged: 3, warnings: ["备注冲突：保留本机备注"] }; });
    await page.getByRole("button", { name: "剪贴板更多操作", exact: true }).click();
    await page.getByRole("button", { name: "导入合并…", exact: true }).click();
    await page.getByText("已导入 2 条新记录，合并 3 条重复记录。", { exact: true }).waitFor();
    await page.getByText("备注冲突：保留本机备注", { exact: true }).waitFor();
    await page.evaluate(() => { window.archiveError = '归档校验失败，原数据未改变。'; });
    await page.getByRole("button", { name: "剪贴板更多操作", exact: true }).click();
    await page.getByRole("button", { name: "导入合并…", exact: true }).click();
    await page.getByRole("alert").filter({ hasText: "归档校验失败" }).waitFor();
    await page.evaluate(() => { window.archiveError = ''; window.importResult = null; });
    await page.getByRole("button", { name: "剪贴板更多操作", exact: true }).click();
    await page.getByRole("button", { name: "导入合并…", exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('[role="alert"]'));
    await page.getByRole("button", { name: "编辑为新记录", exact: true }).click();
    await page.getByLabel("编辑剪贴板副本").fill("新副本：保存后直接选中");
    await page.getByRole("button", { name: "保存新记录", exact: true }).click();
    await page.getByRole("article", { name: "剪贴板预览" }).locator("pre").filter({ hasText: "新副本：保存后直接选中" }).waitFor();
    assert.equal(await page.getByRole("listbox").locator('[data-active="true"] strong').textContent(), "新副本：保存后直接选中");
    assert.equal(await page.evaluate(() => window.entries.find(e => e.id === 'row-0').text), "复制后可以直接粘贴");
    await page.getByRole("listbox").evaluate(element => { element.scrollTop = 2500; });
    const before = await page.getByRole("listbox").evaluate(element => element.scrollTop);
    await page.evaluate(() => window.emit('capture'));
    await page.getByRole("button", { name: /新增 1 条/ }).waitFor();
    assert.equal(await page.getByRole("listbox").evaluate(element => element.scrollTop), before);
    assert.ok(await page.getByRole("listbox").getByRole("option").count() < 35);
    await mkdir(path.resolve(".verification/clipboard-v2"), { recursive: true });
    await page.getByRole("button", { name: /新增 1 条/ }).click();
    await page.screenshot({ path: path.resolve(".verification/clipboard-v2/manager-light.png") });
    await page.evaluate(() => document.documentElement.classList.add('dark'));
    await page.screenshot({ path: path.resolve(".verification/clipboard-v2/manager-dark.png") });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.resolve(".verification/clipboard-v2/manager-narrow.png") });
    await page.goto("https://clipboard-v2.test/?surface=quick");
    await page.getByRole("listbox").getByRole("option").first().waitFor();
    await page.evaluate(() => { window.entries.unshift({ ...window.entries[0], id: 'fresh-capture', title: '刚复制的内容', copiedAt: Date.now() + 1000 }); window.emit('capture'); });
    await page.waitForFunction(() => document.querySelector('[role="option"]')?.id === 'clipboard-fresh-capture');
    await page.getByLabel("搜索剪贴板").fill("测试内容 2");
    await page.getByLabel("搜索剪贴板").press("Space");
    assert.ok((await page.getByLabel("搜索剪贴板").inputValue()).endsWith(" "));
    await page.getByLabel("搜索剪贴板").press("Escape");
    assert.equal(await page.getByLabel("搜索剪贴板").inputValue(), "");
    await page.getByLabel("搜索剪贴板").press("Escape");
    assert.equal(await page.evaluate(() => window.hidden), true);
    await page.getByRole('button', { name: '预览', exact: true }).click();
    await page.getByLabel('剪贴板备注').fill('快捷窗未保存');
    await page.evaluate(() => { window.hidden = false; window.emit('open'); });
    assert.equal(await page.getByLabel('剪贴板备注').inputValue(), '快捷窗未保存');
    await page.getByLabel('剪贴板备注').press('Escape');
    await draftDialog.waitFor();
    assert.equal(await page.evaluate(() => window.hidden), false);
    await draftDialog.getByRole('button', { name: '放弃修改并继续', exact: true }).click();
    await page.waitForFunction(() => window.hidden === true);
    await page.setViewportSize({width:1100,height:900});
    await page.goto("https://clipboard-v2.test/?surface=manager");
    await page.getByRole('listbox').getByRole('option').first().waitFor();
    for (let index=0;index<8;index++) {
      const queries = await page.evaluate(() => window.queries.length);
      await page.getByRole('listbox').evaluate(element => { element.scrollTop=element.scrollHeight; });
      await page.waitForFunction(count => window.queries.length > count, queries);
      await page.evaluate(() => new Promise(requestAnimationFrame));
      assert.ok(await page.locator('.virtualSpace').evaluate(element=>element.offsetHeight<=500*64), 'only five summary pages are retained');
    }
    const firstVisible = () => page.getByRole('listbox').evaluate(list => [...list.querySelectorAll('[role="option"]')].find(row=>row.getBoundingClientRect().bottom>list.getBoundingClientRect().top+4)?.id);
    const anchorId=await firstVisible(); assert.ok(anchorId && !anchorId.endsWith('row-0'));
    await page.evaluate(() => window.emit('mutation'));
    await page.evaluate(() => new Promise(requestAnimationFrame));
    assert.equal(await firstVisible(),anchorId,'mutations preserve the old-history viewport');
    await page.reload();
    await page.waitForFunction(id => document.getElementById(id),anchorId);
    await page.evaluate(() => new Promise(requestAnimationFrame));
    assert.equal(await firstVisible(),anchorId,'reopening restores the actual old-history record');
    const beforeEarlier=await page.evaluate(()=>window.queries.length);
    await page.getByRole('listbox').evaluate(element=>{element.scrollTop=0});
    await page.waitForFunction(count=>window.queries.length>count,beforeEarlier);
    await page.evaluate(() => new Promise(requestAnimationFrame));
    assert.ok(await page.getByRole('listbox').evaluate(element=>element.scrollTop>0),'prepending newer history preserves the visible anchor');
    const renderDesignFixture = async (surface) => {
      await page.evaluate(() => localStorage.clear());
      await page.goto(`https://clipboard-v2.test/?surface=${surface}`);
      await page.waitForFunction(() => window.listeners.size > 0);
      await page.evaluate(() => {
        window.targetName = '文档'; window.enabled = true;
        const base = window.entries[0], now = Date.now();
        const text = '让内容，在需要时就在手边。\n\n快速找回复制过的内容，继续刚才的工作。\n\n✓ 快捷唤起，直接粘贴\n✓ 保留原始格式\n✓ 常用内容固定到屏幕';
        const labels = ['产品发布说明','随身仓交互稿.png','本周交付清单','品牌素材 · 3 个文件','常用回复','https://piora.app/docs','会议纪要','组件样式参考'];
        window.entries = labels.map((title, index) => ({ ...base, id:'design-'+index, title, remark:'', text: index === 0 ? text : index === 4 ? '好的，收到。我来处理。稍后给你反馈进展。' : index === 2 ? '1. 完成剪贴板功能开发  2. 整理设计资源' : '讨论产品路线图、下个版本的重点功能。',
          preview:index===0?'让内容，在需要时就在手边。':index===1?'1080 × 720 · 1.2 MB':index===3?'logo.svg · 图标.zip · 品牌规范.pdf':index===4?'好的，收到。我来处理。稍后给你反馈…':index===5?'Piora 帮助文档 | 使用指南': '本周交付内容、设计资源与产品计划…',
          kind:index===1||index===7?'image':index===3?'files':index===5?'link':'text',
          html:index===0?'<h3>让内容，在需要时就在手边。</h3><p>快速找回复制过的内容，继续刚才的工作。</p><p>✓ 快捷唤起，直接粘贴<br>✓ 保留原始格式<br>✓ 常用内容固定到屏幕</p>':null,
          image:index===1||index===7?{hash:'fixture',mime:'image/png',width:1080,height:720,bytes:1200000}:null,
          formats:index===1||index===7?['image']:index===3?['files']:index===0?['text','html']:['text'],
          files:index===3?[{name:'logo.svg',path:'C:/Design/logo.svg',directory:false,exists:true},{name:'图标.zip',path:'C:/Design/图标.zip',directory:false,exists:true},{name:'品牌规范.pdf',path:'C:/Design/品牌规范.pdf',directory:false,exists:true}]:[],fileCount:index===3?3:0,
          source:{name:index===1||index===7?'截图':index===3?'文件':index===5?'浏览器':'文档',executable:'fixture.exe'},copiedAt:now-index*3600000,starred:index===4,deletedAt:null,
          shelfOrder:index===4?0:index===1?1:index===3?2:null }));
        window.emit('mutation');
      });
      const expected = surface === 'shelf' ? 3 : 8;
      await page.waitForFunction(expected => document.querySelectorAll('[role="option"]').length === expected, expected);
      await page.waitForFunction(() => [...document.images].every(image => image.complete));
    };
    const screenshots = path.resolve('.verification/clipboard-v3'); await mkdir(screenshots, {recursive:true});
    await page.setViewportSize({ width:1200,height:900 });
    await renderDesignFixture('manager');
    await page.getByRole('button',{name:'查看格式',exact:true}).click();
    await page.frameLocator('iframe[title="富文本预览"]').getByText('让内容，在需要时就在手边。').waitFor();
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'manager-light.png')});
    await page.evaluate(() => document.documentElement.classList.add('dark'));
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'manager-dark.png')});
    await page.getByRole('button',{name:'来源',exact:true}).click();
    await page.getByRole('dialog',{name:'按来源筛选'}).waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('dialog').count(),0);
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('listbox').getByRole('option').first().click();
    await page.getByRole('button',{name:'返回列表',exact:true}).click();
    assert.ok(await page.getByRole('listbox').isVisible());
    assert.ok(await page.getByRole('navigation').getByRole('button',{name:'收藏',exact:true}).isVisible());
    await page.getByRole('listbox').getByRole('option').first().click();
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'manager-narrow.png')});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.setViewportSize({width:760,height:540});
    await renderDesignFixture('quick');
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'quick-light.png')});
    await page.evaluate(() => document.documentElement.classList.add('dark'));
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'quick-dark.png')});
    await page.getByRole('button',{name:'预览',exact:true}).click();
    await page.getByRole('article',{name:'剪贴板预览'}).waitFor();
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'quick-preview-dark.png')});
    await page.getByRole('button',{name:'预览',exact:true}).click();
    await page.getByRole('listbox').getByRole('option').first().click({modifiers:['Control']});
    await page.getByRole('listbox').getByRole('option').filter({hasText:'常用回复'}).click({modifiers:['Control']});
    await page.getByText('已选 2 条',{exact:true}).waitFor();
    await page.getByLabel('选择 随身仓交互稿.png', { exact: true }).check();
    assert.equal(await page.getByRole('button', { name: /^合并粘贴/ }).isDisabled(), true, 'mixed representations cannot submit an ambiguous normal paste');
    await page.getByRole('button', { name: '使用文字组（2）', exact: true }).click();
    await page.getByRole('button', { name: '合并复制', exact: true }).click();
    await page.waitForFunction(() => window.commands.findLast(command => command.type === 'copy')?.ids.join(',') === 'design-0,design-4');
    await page.getByRole('button', { name: '恢复完整选择（3）', exact: true }).click();
    await page.getByRole('button', { name: '使用图片和文件组（1）', exact: true }).click();
    await page.getByRole('button', { name: '复制', exact: true }).click();
    await page.waitForFunction(() => window.commands.findLast(command => command.type === 'copy')?.ids.join(',') === 'design-1');
    await page.getByRole('button', { name: '恢复完整选择（3）', exact: true }).click();
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'quick-mixed-groups-dark.png')});
    await page.getByLabel('选择 随身仓交互稿.png', { exact: true }).uncheck();
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'quick-batch-dark.png')});
    await page.evaluate(() => { window.fail=true; });
    await page.getByRole('button',{name:'删除所选记录',exact:true}).click();
    await page.getByRole('alert').waitFor();
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'quick-error-dark.png')});
    await page.setViewportSize({width:360,height:420});
    await renderDesignFixture('shelf');
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'shelf-light.png')});
    await page.evaluate(() => document.documentElement.classList.add('dark'));
    await page.locator('section[data-surface]').screenshot({path:path.join(screenshots,'shelf-dark.png')});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.evaluate(() => { window.budgetState = 'full'; window.emit('status'); });
    await page.getByText('空间预算不足，已暂停新增。历史仍可搜索和复制。', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '复制', exact: true }).isDisabled(), false);
    await page.getByRole('button', { name: '调整容量', exact: true }).click();
    await page.getByRole('dialog', { name: '剪贴板设置', exact: true }).getByText('数据库与索引文件：1.0 MiB', { exact: true }).waitFor();
    await page.getByRole('dialog').getByRole('button', { name: '完成', exact: true }).click();
    await page.evaluate(() => { localStorage.setItem('pi-locale', 'en'); localStorage.removeItem('piora-clipboard-view:v2'); });
    await page.setViewportSize({ width: 1100, height: 800 });
    await page.goto('https://clipboard-v2.test/?surface=manager');
    await page.getByRole('textbox', { name: 'Search clipboard', exact: true }).waitFor();
    await page.waitForFunction(() => window.clipboardLocale === 'en');
    assert.equal(await page.getByRole('article', { name: 'Clipboard preview' }).locator('pre').textContent(), '复制后可以直接粘贴', 'language never translates stored content');
    await page.locator('section[data-surface]').screenshot({ path: path.join(screenshots, 'manager-english.png') });
    await page.getByLabel('Clipboard note', { exact: true }).fill('语言切换时保留的草稿');
    const languageWindow = await page.context().newPage();
    await languageWindow.goto('https://clipboard-v2.test/?surface=shelf');
    await languageWindow.getByRole('button', { name: 'Hide clipboard', exact: true }).waitFor();
    await languageWindow.evaluate(() => localStorage.setItem('pi-locale', 'zh-CN'));
    await page.getByLabel('剪贴板备注', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('剪贴板备注', { exact: true }).inputValue(), '语言切换时保留的草稿', 'cross-window locale sync retains the edit');
    await languageWindow.evaluate(() => localStorage.setItem('pi-locale', 'en'));
    await page.getByLabel('Clipboard note', { exact: true }).waitFor();
    await languageWindow.close();
    for (const [surface, width, height] of [['quick', 760, 540], ['shelf', 360, 420]]) {
      await page.setViewportSize({ width, height }); await page.goto('https://clipboard-v2.test/?surface=' + surface);
      await page.getByRole('button', { name: 'Hide clipboard', exact: true }).waitFor();
      await page.locator('section[data-surface]').screenshot({ path: path.join(screenshots, surface + '-english.png') });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'English layout stays inside the window');
    }
    assert.deepEqual(errors, []);
  } finally { await browser?.close(); assert.ok(path.resolve(directory).startsWith(path.resolve(tmpdir()) + path.sep)); await rm(directory, { recursive: true, force: true }); }
});
