import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, writeFile, readFile, readdir, mkdir, lstat, rm, utimes, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createJiti } from "jiti";
const { ClipboardDragFiles, cleanClipboardTemporaryFiles } = await createJiti(import.meta.url).import("../desktop/src/clipboard-drag-files.ts");
const DAY = 86400_000;

test("drag PNGs share preparation, remain independent of archives and renew their 24-hour lifetime", async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'piora-drag-cache-'));
  const directory = path.join(root, 'drag'), source = path.join(root, 'source');
  let now = Date.now(); const cache = new ClipboardDragFiles(directory, () => now);
  t.after(async () => { await cache.close(); assert.ok(root.startsWith(path.resolve(tmpdir()) + path.sep)); await rm(root, { recursive: true, force: true }); });
  await writeFile(source, 'image fixture');
  const files = await Promise.all(Array.from({ length: 12 }, () => cache.image('hash', source)));
  assert.equal(new Set(files).size, 1); assert.equal((await readdir(directory)).length, 1);
  const original = files[0];
  now += DAY - 1000; assert.equal(await cache.image('hash', source), original);
  now += 2000; await cache.clean(); assert.ok(await lstat(original), '24 hours runs from the last preparation');
  await writeFile(original, 'drop target edited its copy');
  assert.equal(await readFile(source, 'utf8'), 'image fixture');
  const replacement = await cache.image('hash', source);
  assert.notEqual(replacement, original); assert.equal(await readFile(replacement, 'utf8'), 'image fixture');
  await unlink(replacement);
  const recreated = await cache.image('hash', source);
  assert.notEqual(recreated, replacement, 'moved or deleted drop copies are recreated');
  cache.protect([recreated]); now += DAY + 1; await cache.clean();
  assert.ok(await lstat(recreated), 'a prepared window retains its drag capability until use or invalidation');
  cache.retain([recreated, source]); cache.protect([]);
  now += DAY - 1; await cache.clean(); assert.ok(await lstat(recreated), 'actual drag starts a new 24-hour lifetime');
  now += 2; await cache.clean(); assert.deepEqual(await readdir(directory), []);
});

test("cleanup only removes expired app-named files and serializes with new preparations", async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'piora-drag-clean-'));
  const source = path.join(root, 'archive'), directory = path.join(root, 'drag');
  const cache = new ClipboardDragFiles(directory);
  t.after(async () => { await cache.close(); assert.ok(root.startsWith(path.resolve(tmpdir()) + path.sep)); await rm(root, { recursive: true, force: true }); });
  await mkdir(directory); await writeFile(source, 'original');
  const old = new Date(Date.now() - 2 * DAY);
  const owned = '12345678-1234-1234-1234-123456789abc.png';
  await writeFile(path.join(directory, owned + '.tmp'), 'interrupted copy');
  await utimes(path.join(directory, owned + '.tmp'), old, old);
  await writeFile(path.join(directory, 'user-notes.png'), 'keep'); await utimes(path.join(directory, 'user-notes.png'), old, old);
  await mkdir(path.join(directory, owned));
  await cleanClipboardTemporaryFiles(directory);
  assert.deepEqual((await readdir(directory)).sort(), [owned, 'user-notes.png'].sort());
  const clean = cache.clean(), image = cache.image('hash', source);
  await clean; assert.equal(await readFile(await image, 'utf8'), 'original');
});
