import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { chromium } from "playwright-core";
import { buildClipboardUI, clipboardTheme } from "./clipboard-ui-fixture.mjs";
import { setup } from "./clipboard-test-data.mjs";

test("clipboard images use larger thumbnails and a full-resolution viewer without pasting", { timeout: 90000 }, async () => {
  const directory = await mkdtemp(path.join(tmpdir(), "piora-clipboard-image-"));
  const output = path.resolve(".verification/clipboard-images");
  let browser;
  try {
    await mkdir(output, { recursive: true });
    const { bundle, css } = await buildClipboardUI(directory);
    browser = await chromium.launch({ channel: "msedge", headless: true });
    const page = await browser.newPage({ viewport: { width: 760, height: 540 } });
    const errors = []; page.on("pageerror", error => errors.push(error.message));
    const fixture = `${setup}
      window.entries[0]={...window.entries[0],kind:'image',title:'项目界面截图',text:null,html:null,preview:'1600 × 900',image:{width:1600,height:900,bytes:90000},formats:['image']};
      window.assets=[];window.piDesktop.clipboard.historyV2.asset=async(id,thumbnail)=>{window.assets.push({id,thumbnail});return '/fixture-image.svg?thumbnail='+Boolean(thumbnail)};`;
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="#f5f6f8"/><rect width="320" height="900" fill="#e2e5eb"/><text x="50" y="90" font-size="38" font-family="sans-serif" fill="#333">Piora</text><rect x="360" y="42" width="1180" height="110" rx="15" fill="white"/><text x="395" y="112" font-size="36" font-family="sans-serif" fill="#333">Project dashboard</text><rect x="360" y="185" width="570" height="630" rx="15" fill="white"/><rect x="962" y="185" width="578" height="630" rx="15" fill="white"/><path d="M405 625L495 530L600 555L730 330L880 260" fill="none" stroke="#6f7fa6" stroke-width="12"/><text x="400" y="760" font-size="28" font-family="sans-serif" fill="#333">Details visible at original size</text><text x="1000" y="270" font-size="30" font-family="sans-serif" fill="#333">Tasks</text><path d="M1000 340h470m-470 90h470m-470 90h470m-470 90h300" stroke="#d1d5db" stroke-width="18"/></svg>';
    await page.route("https://clipboard-image.test/**", route => {
      const url = new URL(route.request().url());
      if (url.pathname === "/bundle.js") return route.fulfill({ contentType: "text/javascript", body: bundle });
      if (url.pathname === "/fixture-image.svg") return route.fulfill({ contentType: "image/svg+xml", body: svg });
      return route.fulfill({ contentType: "text/html", body: `<!doctype html><meta charset="utf-8"><style>${clipboardTheme}${css}</style><div id="root"></div><script>${fixture}</script><script src="/bundle.js"></script>` });
    });
    await page.goto("https://clipboard-image.test/?surface=quick");
    const row = page.locator("#clipboard-row-0");
    const thumbnail = row.locator(".imageThumbnail");
    await thumbnail.locator("img").waitFor();
    const size = await thumbnail.boundingBox();
    assert.ok(size.width >= 100 && size.height >= 80, "image thumbnails must be discernible rather than icon sized");
    assert.equal(await thumbnail.locator("img").evaluate(node => getComputedStyle(node).objectFit), "contain");
    const next = await page.locator("#clipboard-row-1").boundingBox();
    const first = await row.boundingBox();
    assert.ok(next.y >= first.y + first.height - 1, "virtualized rows must account for taller images");
    await page.screenshot({ path: path.join(output, "image-list.png") });
    const open = page.getByRole("button", { name: "查看大图：项目界面截图", exact: true });
    await open.click();
    const dialog = page.getByRole("dialog", { name: "图片大图预览", exact: true });
    await dialog.locator("img").waitFor();
    assert.equal(await page.evaluate(() => window.commands.length), 0, "opening the image must not copy or paste");
    assert.ok(await page.evaluate(() => window.assets.some(asset => asset.id === "row-0" && !asset.thumbnail)), "viewer loads the full asset");
    const imageBounds = await dialog.locator("img").boundingBox();
    assert.ok(imageBounds.width > 600 && imageBounds.height > 300, "preview uses the window rather than the sidebar");
    await page.screenshot({ path: path.join(output, "image-viewer.png") });
    await dialog.getByRole("button", { name: "100%", exact: true }).click();
    assert.equal(await dialog.locator("img").evaluate(node => node.getBoundingClientRect().width), 1600);
    assert.equal(await dialog.locator(".imageViewerCanvas").evaluate(node => node.scrollWidth > node.clientWidth), true);
    await dialog.getByRole("combobox", { name: "图片缩放", exact: true }).selectOption("2");
    assert.equal(await dialog.locator("img").evaluate(node => node.getBoundingClientRect().width), 3200);
    await dialog.getByRole("button", { name: "适应窗口", exact: true }).click();
    await dialog.getByLabel("图片预览区域").focus();
    await page.keyboard.press("Enter");
    await dialog.getByRole("status").filter({ hasText: "已复制" }).waitFor();
    assert.deepEqual(await page.evaluate(() => window.commands.filter(command => command.type === "copy").map(command => command.ids)), [["row-0"]]);
    assert.equal(await page.evaluate(() => window.commands.filter(command => command.type === "paste").length), 0);
    await page.keyboard.press("Escape");
    await dialog.waitFor({ state: "hidden" });
    assert.equal(await open.evaluate(node => node === document.activeElement), true, "closing restores focus to the preview entry point");
    assert.equal(await page.evaluate(() => Boolean(window.hidden)), false, "Escape closes only the viewer");
    await page.setViewportSize({ width: 360, height: 540 });
    await open.click();
    await dialog.waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.keyboard.press("Escape");
    await page.setViewportSize({ width: 760, height: 640 });
    await page.evaluate(() => localStorage.setItem("piora-clipboard-view:v2", JSON.stringify({ width: 240, preview: true })));
    await page.goto("https://clipboard-image.test/?surface=manager");
    await page.locator("#clipboard-row-0 .imageThumbnail img").waitFor();
    assert.equal(await page.getByRole("listbox").evaluate(node => node.scrollWidth <= node.clientWidth), true, "narrow preview sidebars must not overflow");
    await page.getByRole("button", { name: "查看大图", exact: true }).click();
    await dialog.waitFor();
    assert.equal(await page.evaluate(() => window.commands.length), 0, "the detail preview entry point only opens the viewer");
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    assert.ok(path.resolve(directory).startsWith(path.resolve(tmpdir()) + path.sep) && path.basename(directory).startsWith("piora-clipboard-image-"));
    await rm(directory, { recursive: true, force: true });
  }
});
