import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { createJiti } from "jiti";
import { chromium } from "playwright-core";

const require = createRequire(import.meta.url), repo = path.resolve(import.meta.dirname, "..");
const { webpack } = require("next/dist/compiled/webpack/webpack.js");
const jiti = createJiti(import.meta.url, { alias: { "@": repo } });
const previewRoute = await jiti.import("../app/api/harmony/scenario/preview/route.ts");
const { scenarioTemplates, bindScenarioTemplate } = await jiti.import("./harmony/scenario/templates.ts");

test("scenario editor previews real admission rules, preserves targets, and dispatches only an explicitly run plan", { timeout: 180000 }, async () => {
  const root = await mkdtemp(path.join(tmpdir(), "piora-scenario-editor-"));
  const previousToken = process.env.PI_DESKTOP_TOKEN, token = randomBytes(32).toString("hex");
  process.env.PI_DESKTOP_TOKEN = token;
  let browser;
  try {
    await writeFile(path.join(root, "loader.cjs"), `const ts=require(${JSON.stringify(require.resolve("typescript"))});module.exports=s=>ts.transpileModule(s,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText`);
    await writeFile(path.join(root, "css.cjs"), 'module.exports=s=>"export default "+JSON.stringify(Object.fromEntries([...s.matchAll(/\\.([a-zA-Z][\\w-]*)/g)].map(m=>[m[1],m[1]])))');
    await writeFile(path.join(root, "entry.tsx"), `import React,{useState} from "react";import {flushSync} from "react-dom";import {createRoot} from "react-dom/client";import {ScenarioWorkbench} from "@/components/workspace/harmony/ScenarioWorkbench";function Fixture(){const[canControl,setCanControl]=useState(false);const[active,setActive]=useState(true);window.setControl=value=>flushSync(()=>setCanControl(value));window.setActive=value=>flushSync(()=>setActive(value));const acquire=async()=>{window.acquireCount=(window.acquireCount??0)+1;if(window.delayLease)await new Promise(resolve=>window.releaseLease=resolve);return "fixture-lease"};return <div className="root workbench" style={{height:"100vh",overflow:"auto",padding:12}}><ScenarioWorkbench serial="phone-A" active={active} canControl={canControl} ensureControl={acquire} chinese={true}/></div>};createRoot(document.getElementById("root")).render(<Fixture/>);`);
    const compiler = webpack({ mode: "development", target: "web", devtool: false, entry: path.join(root, "entry.tsx"), output: { path: root, filename: "bundle.js" },
      resolve: { extensions: [".tsx", ".ts", ".js"], modules: [path.join(repo, "node_modules")], alias: { "@": repo } },
      module: { rules: [{ test: /\.tsx?$/, exclude: /node_modules/, use: path.join(root, "loader.cjs") }, { test: /\.css$/, use: path.join(root, "css.cjs") }] } });
    await new Promise((resolve, reject) => compiler.run((error, stats) => compiler.close(() => error || stats.hasErrors() ? reject(error || Error(stats.toString({ all: false, errors: true }))) : resolve())));
    const bundle = await readFile(path.join(root, "bundle.js")), css = await readFile(path.join(repo, "components/workspace/HarmonyPanel.module.css"), "utf8");
    browser = await chromium.launch({ channel: process.platform === "win32" ? "msedge" : "chromium", headless: true });
    const page = await browser.newPage({ viewport: { width: 900, height: 850 }, acceptDownloads: true });
    const errors = [], executions = [], previews = [], nativeDialogs = [];
    let delayPreview, resolvePreview, failApps = false, delayExecution, resolveExecution, failProgress = false;
    const progressRequests = [], fixturePng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=", "base64");
    const fixtureScreenshot = { kind: "screenshot", serial: "phone-A", filename: "phone-A-fixture.png", path: "C:\\fixture\\phone-A-fixture.png", width: 1, height: 1, size: fixturePng.length, createdAt: new Date().toISOString() };
    page.on("pageerror", error => errors.push(error.message));
    page.on("dialog", async dialog => { nativeDialogs.push(dialog.type()); await dialog.dismiss(); });
    await page.route("https://scenario-editor.test/**", async route => {
      const request = route.request(), url = new URL(request.url());
      if (url.pathname === "/bundle.js") return route.fulfill({ contentType: "text/javascript", body: bundle });
      if (!url.pathname.startsWith("/api/")) return route.fulfill({ contentType: "text/html", body: `<meta charset="utf-8"><style>:root{--bg:#fff;--bg-panel:#f7f7f8;--border:#ddd;--text:#18181b;--text-dim:#71717a;--accent:#2563eb;--text-xs:12px;--text-base:14px}body{margin:0;font:14px system-ui}${css}</style><div id="root"></div><script src="/bundle.js"></script>` });
      const input = request.method() === "POST" ? request.postDataJSON() : undefined;
      if (url.pathname === "/api/harmony/media/preview") return route.fulfill({ contentType: "image/png", body: fixturePng });
      if (url.pathname === "/api/harmony/apps") return route.fulfill(failApps ? { status: 503, json: { error: { message: "fixture app scan unavailable" } } } : { json: { applications: ["dev.piora.first", "dev.piora.second"].filter(bundle => !url.searchParams.get("bundleName") || url.searchParams.get("bundleName") === bundle).map(bundleName => ({ bundleName, label: bundleName, abilities: ["EntryAbility"] })) } });
      if (url.pathname === "/api/harmony/templates") return route.fulfill({ json: input ? { steps: bindScenarioTemplate(input.id, input.parameters) } : { templates: scenarioTemplates } });
      if (url.pathname === "/api/harmony/scenario/preview") {
        previews.push(input);
        if (delayPreview) await delayPreview;
        const response = await previewRoute.POST(new Request("http://localhost:30141/api/harmony/scenario/preview", { method: "POST", headers: { host: "localhost:30141", "content-type": "application/json", "x-pi-desktop-token": token }, body: JSON.stringify(input) }));
        return route.fulfill({ status: response.status, json: await response.json() }).catch(() => {});
      }
      if (url.pathname === "/api/harmony/scenario") {
        if (!input) {
          progressRequests.push(url.searchParams.get("clientRunId"));
          if (failProgress) return route.fulfill({ status: 503, json: { error: { message: "fixture progress unavailable" } } });
          const run = executions.find(run => run.clientRunId === url.searchParams.get("clientRunId"));
          return route.fulfill({ json: { executions: run ? [{ serial: run.serial, clientRunId: run.clientRunId, steps: run.steps.map((step, index) => ({ index, action: step.action, status: index === 0 ? "passed" : "running", durationMs: 7, ...(step.action === "capture_screenshot" ? { screenshot: fixtureScreenshot } : {}) })) }] : [] } });
        }
        executions.push(input);
        if (delayExecution) await delayExecution;
        return route.fulfill({ json: { result: { executionId: "execution-1", status: "passed", ...(input.policy.collectLogs ? { logs: { status: "failed", capturedAt: new Date().toISOString(), source: "device-tail", limit: 200, truncated: false, entries: [], error: { code: "CAPABILITY_UNAVAILABLE", message: "fixture log capture unavailable" } } } : {}), ...(input.policy.captureFinalScreenshot ? { finalScreenshot: fixtureScreenshot } : {}), steps: input.steps.map((step, index) => ({ index, action: step.action, status: "passed", durationMs: 7, ...(step.action === "capture_screenshot" ? { screenshot: fixtureScreenshot } : {}) })) } } }).catch(() => {});
      }
      throw Error(`Unexpected fixture request: ${url.pathname}`);
    });
    await page.goto("https://scenario-editor.test/");
    const app = page.getByRole("combobox", { name: "测试应用", exact: true });
    await app.selectOption("dev.piora.first");
    await page.getByLabel("预期首页文字", { exact: true }).fill("欢迎");
    await page.getByRole("button", { name: "编辑模板步骤", exact: true }).click();
    const editor = page.getByRole("region", { name: "场景步骤编辑器", exact: true });
    await editor.waitFor();
    const step = index => editor.getByRole("group", { name: `第 ${index} 步`, exact: true });
    assert.equal(await step(1).getByLabel("应用包名", { exact: true }).inputValue(), "dev.piora.first");
    await step(2).getByLabel("检查点名称", { exact: true }).fill("after-launch");
    assert.equal(await page.getByText(/参数校验通过/).count(), 0, "editing revokes the previous validation");
    await editor.getByRole("button", { name: "添加步骤", exact: true }).click();
    await step(3).getByRole("combobox", { name: "动作", exact: true }).selectOption("input_text");
    await step(3).getByLabel("控件 ID", { exact: true }).fill("editor");
    await step(3).getByRole("textbox", { name: "输入内容", exact: true }).fill("中文 $ ` {{literal}}");
    await step(3).getByRole("button", { name: "上移第 3 步", exact: true }).click();
    assert.equal(await step(2).getByRole("textbox", { name: "输入内容", exact: true }).inputValue(), "中文 $ ` {{literal}}");
    await app.selectOption("dev.piora.second");
    assert.equal(await step(1).getByLabel("应用包名", { exact: true }).inputValue(), "dev.piora.first", "choosing the default app does not retarget existing steps");
    await page.getByRole("checkbox", { name: "结束时采集截图", exact: true }).check();
    await page.getByRole("button", { name: "预览场景", exact: true }).click();
    await page.getByText("参数校验通过 · 3 个步骤", { exact: true }).waitFor();
    assert.deepEqual(previews.at(-1).steps.map(step => step.action), ["launch_app", "input_text", "checkpoint"]);
    assert.equal(previews.at(-1).steps[1].text, "中文 $ ` {{literal}}");
    assert.equal(await page.evaluate(() => window.acquireCount ?? 0), 0);
    assert.equal(executions.length, 0);
    assert.equal(await page.getByRole("button", { name: "运行测试", exact: true }).isDisabled(), true, "offline editing and preview never enable device execution");
    await page.evaluate(() => window.setControl(true));
    await page.getByRole("button", { name: "运行测试", exact: true }).click();
    await page.getByText("测试通过", { exact: true }).waitFor();
    assert.equal(executions.length, 1); assert.equal(executions[0].serial, "phone-A"); assert.equal(executions[0].policy.captureFinalScreenshot, true);
    assert.equal(executions[0].steps[0].bundleName, "dev.piora.first");
    const completionImage = page.getByRole("img", { name: "场景结束时的设备截图", exact: true });
    await completionImage.scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector('img[alt="场景结束时的设备截图"]')?.naturalWidth === 1);
    const downloadPromise = page.waitForEvent("download");
    await page.getByRole("button", { name: "导出本次结果", exact: true }).click();
    const download = await downloadPromise; assert.equal(download.suggestedFilename(), "harmony-scenario-execution-1.json");
    await download.delete();
    await step(2).getByLabel("控件 ID", { exact: true }).fill("");
    await page.getByRole("button", { name: "运行测试", exact: true }).click();
    await page.getByRole("alert").waitFor();
    assert.equal(executions.length, 1); assert.equal(await page.evaluate(() => window.acquireCount), 1, "invalid steps fail before acquiring control");
    await step(2).getByLabel("控件 ID", { exact: true }).fill("editor");
    await page.evaluate(() => window.delayLease = true);
    await page.getByRole("button", { name: "运行测试", exact: true }).click();
    await page.waitForFunction(() => typeof window.releaseLease === "function");
    assert.equal(await editor.getByRole("button", { name: "添加步骤", exact: true }).isDisabled(), true);
    await page.getByRole("button", { name: "停止测试", exact: true }).click();
    await page.evaluate(() => { window.delayLease = false; window.releaseLease(); });
    await page.getByRole("alert").filter({ hasText: "已请求取消" }).waitFor();
    assert.equal(executions.length, 1, "cancellation during acquisition must not dispatch the plan");
    delayPreview = new Promise(resolve => resolvePreview = resolve);
    const previewRequest = page.waitForRequest(request => request.url().endsWith("/scenario/preview"));
    await page.getByRole("button", { name: "预览场景", exact: true }).click(); await previewRequest;
    await page.evaluate(() => window.setActive(false));
    resolvePreview(); delayPreview = null;
    await page.getByRole("alert").filter({ hasText: "已请求取消" }).waitFor();
    assert.equal(executions.length, 1);
    await page.evaluate(() => window.setActive(true));
    await step(3).getByRole("combobox", { name: "动作", exact: true }).selectOption("clear_app_data");
    assert.equal(await step(3).getByLabel("应用包名", { exact: true }).inputValue(), "dev.piora.second");
    const beforeDanger = await page.evaluate(() => window.acquireCount);
    await page.getByRole("button", { name: "运行测试", exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('.primaryButton')?.disabled);
    assert.equal(executions.length, 2); assert.equal(await page.evaluate(() => window.acquireCount), beforeDanger + 1);
    assert.equal(executions.at(-1).steps[2].action, "clear_app_data");
    assert.equal(executions.at(-1).steps[2].bundleName, "dev.piora.second");
    assert.deepEqual(nativeDialogs, [], "the selected plan executes directly after an explicit run click");
    await step(3).getByRole("button", { name: "删除第 3 步", exact: true }).click();
    assert.equal(await editor.getByRole("group", { name: /^第 \d+ 步$/ }).count(), 2);
    failApps = true;
    await page.getByRole("button", { name: "刷新", exact: true }).click();
    await page.getByRole("alert").filter({ hasText: "fixture app scan unavailable" }).waitFor();
    assert.equal(await step(1).getByLabel("应用包名", { exact: true }).inputValue(), "dev.piora.first");
    await page.getByRole("button", { name: "预览场景", exact: true }).click();
    await page.getByText("参数校验通过 · 2 个步骤", { exact: true }).waitFor();
    assert.equal(executions.length, 2, "an app scan failure preserves custom steps and allows parameter-only preview");
    await step(1).getByRole("combobox", { name: "动作", exact: true }).selectOption("capture_screenshot");
    await step(1).getByLabel("截图名称（可选）", { exact: true }).fill("after-open");
    await page.getByRole("checkbox", { name: "报告包含设备日志片段（最多 200 行）", exact: true }).check();
    delayExecution = new Promise(resolve => resolveExecution = resolve);
    await page.getByRole("button", { name: "运行测试", exact: true }).click();
    const progressPanel = page.getByRole("region", { name: "场景执行进度", exact: true });
    await progressPanel.getByText("已完成 1/2 步", { exact: true }).waitFor();
    assert.match(executions.at(-1).clientRunId, /^[a-f0-9-]{36}$/);
    assert.equal(progressRequests.at(-1), executions.at(-1).clientRunId);
    const thumbnail = progressPanel.getByRole("img", { name: "本步骤采集的设备截图", exact: true });
    await thumbnail.scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector('img[alt="本步骤采集的设备截图"]')?.naturalWidth === 1);
    failProgress = true;
    await progressPanel.getByText(/进度读取失败.*fixture progress unavailable/).waitFor();
    assert.equal(await thumbnail.isVisible(), true, "a failed progress read preserves the last confirmed screenshot");
    failProgress = false;
    await progressPanel.getByText(/进度读取失败/).waitFor({ state: "hidden" });
    resolveExecution(); delayExecution = null;
    await page.getByText("测试通过", { exact: true }).waitFor();
    assert.equal(await progressPanel.count(), 0);
    assert.equal(executions.at(-1).policy.collectLogs, true);
    await page.getByText("报告日志片段 · 0 行", { exact: true }).click();
    await page.getByText(/日志未采集：fixture log capture unavailable/).waitFor();
    const finalImage = page.getByRole("img", { name: "本步骤采集的设备截图", exact: true });
    assert.equal(await finalImage.count(), 1);
    await finalImage.scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector('img[alt="本步骤采集的设备截图"]')?.naturalWidth === 1);
    assert.match(await finalImage.getAttribute("src"), /serial=phone-A.*filename=phone-A-fixture.png/);
    await page.setViewportSize({ width: 360, height: 850 });
    assert.equal(await editor.evaluate(element => element.scrollWidth <= element.clientWidth + 1), true, "the editor remains usable in a narrow workbench");
    await page.getByRole("button", { name: "返回模板模式", exact: true }).click();
    await editor.waitFor({ state: "hidden" });
    assert.deepEqual(nativeDialogs, [], "switching the selected plan opens no native confirmation");
    assert.deepEqual(errors, []);
  } finally {
    await browser?.close();
    if (previousToken === undefined) delete process.env.PI_DESKTOP_TOKEN; else process.env.PI_DESKTOP_TOKEN = previousToken;
    assert.equal(path.dirname(root), path.resolve(tmpdir())); await rm(root, { recursive: true, force: true });
  }
});
