import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, writeFile, readFile, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { chromium } from "playwright-core";

const require = createRequire(import.meta.url);
const { webpack } = require("next/dist/compiled/webpack/webpack.js");
const repo = path.resolve(import.meta.dirname, "..");
test("JSON editor: real browser search, replace, undo, folds, locales and layouts", { timeout: 120_000 }, async () => {
  const root = await mkdtemp(path.join(tmpdir(), "piora-json-editor-"));
  let browser;
  try {
    await writeFile(path.join(root, "loader.cjs"), `const ts=require(${JSON.stringify(require.resolve("typescript"))});module.exports=function(source){return ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText}`);
    await writeFile(path.join(root, "empty.cjs"), 'module.exports=function(){return ""}');
    await writeFile(path.join(root, "i18n.js"), 'import React from "react";export const Context=React.createContext("zh-CN");export function useI18n(){return {locale:React.useContext(Context)}}');
    await writeFile(path.join(root, "entry.tsx"), `import React from "react";import {createRoot} from "react-dom/client";import {JsonCodeEditor} from ${JSON.stringify(path.join(repo, "components/JsonCodeEditor.tsx"))};import {Context} from "./i18n.js";
const original=JSON.stringify({user:{name:"Alice",city:"Hangzhou",active:true,score:98.5,note:null},members:["Alice","ALICE","AliceCo"],message:"Welcome Alice"},null,2);window.original=original;
function App(){const [value,setValue]=React.useState(original);const [locale,setLocale]=React.useState("zh-CN");const [id,setId]=React.useState("one");window.setLocale=setLocale;window.setDoc=(id,text)=>{setId(id);setValue(text)};window.editorValue=value;return <Context.Provider value={locale}><JsonCodeEditor className="editorHost" documentId={id} maxLength={200000} onLimitExceeded={()=>{}} ariaLabel="JSON 正文" onChange={setValue} onPasteText={()=>null} onShortcut={()=>{}} placeholder="JSON" value={value} wrap={false}/></Context.Provider>}createRoot(document.getElementById("root")).render(<App/>);`);
    const compiler = webpack({ mode: "development", target: "web", devtool: false, entry: path.join(root, "entry.tsx"), output: { path: root, filename: "bundle.js" }, resolve: { extensions: [".tsx", ".ts", ".js"], modules: [path.join(repo, "node_modules"), "node_modules"], alias: { "@/hooks/useI18n": path.join(root, "i18n.js"), "@": repo } }, module: { rules: [{ test: /\.tsx?$/, exclude: /node_modules/, use: path.join(root, "loader.cjs") }, { test: /\.css$/, use: path.join(root, "empty.cjs") }] } });
    await new Promise((resolve, reject) => compiler.run((error, stats) => compiler.close(() => error || stats.hasErrors() ? reject(error || new Error(stats.toString({ all: false, errors: true }))) : resolve())));
    const bundle = await readFile(path.join(root, "bundle.js"), "utf8");
    const css = (await readFile(path.join(repo, "components/JsonWorkbench.module.css"), "utf8")).replace(/:global\(([^)]+)\)/g, "$1") + await readFile(path.join(repo, "components/EditorSearch.css"), "utf8");
    browser = await chromium.launch({ channel: "msedge", headless: true });
    const page = await browser.newPage({ viewport: { width: 1100, height: 760 } });
    const errors = []; page.on("pageerror", (error) => errors.push(error.message));
    await page.route("http://editor.test/**", (route) => route.fulfill({ contentType: "text/html", body: `<!doctype html><style>:root{--bg:#fff;--bg-panel:#f7f8fa;--bg-hover:#eef0f3;--border:#e2e5e9;--text:#263445;--text-muted:#586476;--text-dim:#747e8c;--accent:#dc7745;--ui-font-size:14px;--font-mono:Consolas,monospace;--font-ui:system-ui}html.dark{--bg:#20252d;--bg-panel:#282e38;--bg-hover:#353e4a;--border:#414a58;--text:#e4e9f0;--text-muted:#bac3d0;--text-dim:#99a5b5}body{margin:40px;background:var(--bg-panel)}#root{height:640px;border:1px solid var(--border);border-radius:10px;overflow:hidden}${css}</style><div id="root"></div>` }));
    await page.goto("http://editor.test"); await page.addScriptTag({ content: bundle });
    const editor = page.locator(".cm-content"); await editor.waitFor();
    await editor.click(); await page.keyboard.press("Control+Home"); await page.keyboard.press("Control+f");
    const find = page.locator('input[name="search"]'); const replace = page.locator('input[name="replace"]');
    await find.fill("Alice");
    assert.match(await page.locator(".piora-search-count").textContent(), /5/);
    await page.getByRole("button", { name: "区分大小写", exact: true }).click();
    assert.match(await page.locator(".piora-search-count").textContent(), /4/);
    await page.getByRole("button", { name: "全词匹配", exact: true }).click();
    assert.match(await page.locator(".piora-search-count").textContent(), /3/);
    await find.press("Enter"); assert.match(await page.locator(".piora-search-count").textContent(), /^1 \/ 3/);
    await find.press("Shift+Enter"); assert.match(await page.locator(".piora-search-count").textContent(), /^3 \/ 3/);
    await replace.fill("Bob"); await page.getByRole("button", { name: "全部替换", exact: true }).click();
    const changed = await page.evaluate(() => window.editorValue); assert.equal((changed.match(/Bob/g) ?? []).length, 3); assert.match(changed, /AliceCo/);
    await find.press("Escape"); await page.keyboard.press("Control+z"); assert.equal(await page.evaluate(() => window.editorValue), await page.evaluate(() => window.original));
    await page.keyboard.press("Control+h"); await page.getByRole("button", { name: "正则表达式", exact: true }).click(); await find.fill("[");
    assert.equal(await find.getAttribute("aria-invalid"), "true"); assert.equal(await page.getByRole("button", { name: "全部替换", exact: true }).isDisabled(), true);
    await find.fill("Ali(ce)"); await replace.fill("Eli$1"); await page.getByRole("button", { name: "全部替换", exact: true }).click(); assert.match(await page.evaluate(() => window.editorValue), /Elice/);
    await find.press("Escape"); await page.keyboard.press("Control+z");
    const fold = page.locator(".piora-fold-chevron:visible").first(); await fold.click(); assert.equal(await page.locator(".piora-fold-placeholder").count(), 1);
    await page.locator(".piora-fold-placeholder").click(); assert.equal(await page.locator(".piora-fold-placeholder").count(), 0);
    await editor.click(); await page.keyboard.press("Control+f"); await find.fill("Alice");
    const output = path.join(repo, "test-results/json-editor"); await mkdir(output, { recursive: true });
    await page.screenshot({ path: path.join(output, "light.png") });
    await page.evaluate(() => document.documentElement.classList.add("dark")); await page.screenshot({ path: path.join(output, "dark.png") });
    await page.evaluate(() => window.setLocale("en")); await page.getByRole("button", { name: "Replace all", exact: true }).waitFor();
    await page.setViewportSize({ width: 440, height: 760 }); await page.screenshot({ path: path.join(output, "narrow.png") });
    assert.equal(await page.locator(".piora-search").evaluate((el) => el.scrollWidth <= el.clientWidth), true);
    await page.evaluate(() => window.setDoc("two", '{"other":123}')); await page.waitForFunction(() => window.editorValue.includes("other"));
    await page.locator(".cm-content").click(); await page.keyboard.press("Control+z"); assert.equal(await page.evaluate(() => window.editorValue), '{"other":123}');
    assert.deepEqual(errors, []);
  } finally { await browser?.close(); assert.equal(path.dirname(root), path.resolve(tmpdir())); await rm(root, { recursive: true, force: true }); }
});
