import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, rm, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createJiti } from "jiti";
import { ProjectTrustStore } from "@earendil-works/pi-coding-agent";
const jiti = createJiti(import.meta.url, { alias: { "@": resolve(".") } });
const { GET, PUT } = await jiti.import("../app/api/mcp/route.ts");

test("native MCP API requires origin, workspace and existing trust while keeping stored secrets private", async t => {
  const root = await mkdtemp(join(tmpdir(), "piora-mcp-route-")), agent = join(root, "agent"), cwd = join(root, "cwd");
  await mkdir(agent); await mkdir(cwd);
  const previous = process.env.PI_CODING_AGENT_DIR; process.env.PI_CODING_AGENT_DIR = agent;
  globalThis.__piAllowedRootsCache = { roots: new Set([cwd.replace(/\\/g, "/")]), expiresAt: Date.now() + 60000 };
  t.after(async () => { globalThis.__piAllowedRootsCache = undefined; if (previous === undefined) delete process.env.PI_CODING_AGENT_DIR; else process.env.PI_CODING_AGENT_DIR = previous; await rm(root, { recursive: true, force: true }); });
  const put = (body, headers = {}) => PUT(new Request("http://localhost:30141/api/mcp", { method: "PUT", headers: { host: "localhost:30141", origin: "http://localhost:30141", "content-type": "application/json", ...headers }, body: JSON.stringify({ cwd, ...body }) }));
  const get = async () => GET(new Request(`http://localhost:30141/api/mcp?cwd=${encodeURIComponent(cwd)}`, { headers: { host: "localhost:30141" } }));
  assert.equal((await put({ action: "integration", enabled: true }, { origin: "https://hostile.invalid" })).status, 403);
  assert.equal((await put({ action: "integration", enabled: true }, { "content-type": "text/plain" })).status, 415);
  assert.equal((await put({ action: "integration", enabled: true, cwd: root })).status, 403);
  assert.equal((await put({ action: "server", scope: "project", name: "local", config: { command: "node" } })).status, 400);
  const saved = await put({ action: "server", scope: "global", name: "private", config: { url: "https://fixture.invalid/mcp?PRIVATE_QUERY", headers: { Authorization: "PRIVATE_HEADER" }, oauth: { clientId: "fixture", clientSecret: "PRIVATE_OAUTH" }, exposure: "codemode", enabled: false } });
  assert.equal(saved.status, 200);
  const result = await (await get()).json();
  assert.equal(result.reloadRequired, false); assert.equal(result.live, false); assert.equal(result.owner, "not-started");
  assert.equal(result.servers[0].endpoint, "https://fixture.invalid");
  assert.doesNotMatch(JSON.stringify(result), /PRIVATE_HEADER|PRIVATE_OAUTH|PRIVATE_QUERY|clientSecret|headers/);
  assert.match(await readFile(join(agent, "mcp.json"), "utf8"), /PRIVATE_HEADER/);
  new ProjectTrustStore(agent).set(cwd, true);
  assert.equal((await put({ action: "server", scope: "project", name: "private", exposure: "deferred" })).status, 200);
  const overridden = await (await get()).json();
  assert.equal(overridden.servers[0].exposure, "deferred"); assert.ok(overridden.servers[0].override.endsWith("mcp.json"));
  assert.doesNotMatch(await readFile(join(cwd, ".pi/mcp.json"), "utf8"), /PRIVATE_HEADER|PRIVATE_OAUTH/);
  assert.equal((await put({ action: "server", scope: "project", name: "forbidden", config: { url: "https://fixture.invalid", auth: { provider: "fixture" } } })).status, 400);
  const unsafe = await put({ action: "server", scope: "global", name: "invalid", config: { url: "https://fixture.invalid", oauth: { callbackUrl: "INVALID_PRIVATE_TOKEN" } } });
  assert.equal(unsafe.status, 400); assert.doesNotMatch(JSON.stringify(await unsafe.json()), /INVALID_PRIVATE_TOKEN/);
  assert.equal((await put({ action: "approve-registered", name: "unseen", enabled: true })).status, 400);
});
