import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { createJiti } from "jiti";
const jiti = createJiti(import.meta.url, { alias: { "@": path.resolve(import.meta.dirname, "..") } });
const { ShellStore } = await jiti.import("./shell/store.ts");
const { allowFileRoot } = await jiti.import("./file-access.ts");
const { getLegacyTerminal } = await jiti.import("./shell/legacy.ts");
const { createShell, listShells } = await jiti.import("./shell/registry.ts");
const { POST } = await jiti.import("../app/api/terminal/route.ts");
const { GET } = await jiti.import("../app/api/terminal/events/route.ts");
const { handleShellRequest } = await jiti.import("./shell/http.ts");

test("legacy HTTP/SSE uses one pinned managed terminal and respects Agent ownership", { timeout: 60000 }, async () => {
  const directory = await mkdtemp(path.join(tmpdir(), "piora-shell-legacy-"));
  const store = new ShellStore(directory, false);
  globalThis.__pioraShellStore = store;
  allowFileRoot(directory);
  const sessions = [];
  let reader;
  const post = body => POST(new Request("http://localhost/api/terminal", { method: "POST", headers: { "Content-Type": "application/json", Host: "localhost", Origin: "http://localhost" }, body: JSON.stringify({ cwd: directory, ...body }) }));
  try {
    const [first, same] = await Promise.all([getLegacyTerminal(directory), getLegacyTerminal(directory)]);
    sessions.push(first); assert.equal(first.state.id, same.state.id);
    const second = await createShell(directory); sessions.push(second);
    const childDirectory = path.join(directory, "subproject"); await mkdir(childDirectory);
    const background = await createShell(childDirectory, first.state.profile.executable, directory); sessions.push(background);
    assert.ok((await listShells(directory)).some(item => item.id === background.state.id), "a background PTY in a subdirectory stays in its originating workspace");
    assert.equal(background.state.cwd, childDirectory);
    await second.savePreferences({ title: "Another active terminal" });
    assert.equal((await getLegacyTerminal(directory)).state.id, first.state.id, "other terminal updates must not retarget a cwd-only client");
    const start = await post({ action: "start" }); assert.equal(start.status, 200);
    const state = await start.json(); assert.equal(state.connected, true); assert.equal(state.cwd, directory); assert.ok(state.shell);
    const stream = await GET(new Request(`http://localhost/api/terminal/events?cwd=${encodeURIComponent(directory)}`, { headers: { Host: "localhost" } }));
    assert.equal(stream.status, 200); reader = stream.body.getReader();
    const frame = new TextDecoder().decode((await reader.read()).value);
    const snapshot = JSON.parse(frame.split("data: ")[1]);
    assert.equal(snapshot.type, "snapshot"); assert.equal(snapshot.connected, true); assert.equal(snapshot.output, first.snapshot().output);
    const command = first.state.profile.kind === "powershell" ? "Write-Output 'LEGACY_BRIDGE'" : "echo LEGACY_BRIDGE";
    const clientRequestId = randomUUID();
    assert.equal((await post({ action: "run", command, clientRequestId })).status, 200);
    assert.equal((await post({ action: "run", command, clientRequestId })).status, 200);
    const deadline = Date.now() + 10000;
    while (first.state.activeCommandId && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 20));
    assert.equal(first.snapshot().commands.length, 1); assert.equal(second.snapshot().commands.length, 0);
    assert.equal(first.snapshot().commands[0].status, "completed");
    assert.match(first.snapshot().commands[0].output, /LEGACY_BRIDGE/);
    const ownership = randomUUID(); first.claim(ownership);
    const busy = await post({ action: "run", command }); assert.equal(busy.status, 409, await busy.text());
    assert.equal((await post({ action: "input", data: "echo bypass\r" })).status, 409);
    first.release(ownership);
    const denied = await POST(new Request("http://localhost/api/terminal", { method: "POST", headers: { "Content-Type": "application/json", Host: "localhost", Origin: "https://untrusted.invalid" }, body: JSON.stringify({ cwd: directory, action: "run", command }) }));
    assert.equal(denied.status, 403);
    assert.equal((await post({ action: "stop" })).status, 200); assert.equal(first.state.connected, false);
    const retryId = randomUUID();
    await store.accept(first.state.id, retryId, (await import("node:crypto")).createHash("sha256").update(JSON.stringify({ command: "formerAlias", runId: null })).digest("hex"), "command", { id: "old-alias-command", command: "formerAlias", status: "completed" });
    const retry = (mode, text = "formerAlias") => handleShellRequest(new Request("http://localhost/api/shell", { method: "POST", headers: { "Content-Type": "application/json", Host: "localhost", Origin: "http://localhost" }, body: JSON.stringify({ action: "submit", mode, text, clientRequestId: retryId }) }), ["sessions", first.state.id, "actions"]);
    const recovered = await retry("auto");
    assert.equal(recovered.status, 200); assert.equal((await recovered.json()).command.id, "old-alias-command");
    assert.equal(first.state.connected, false, "recovering a receipt must not restart or execute the removed alias");
    assert.equal((await retry("agent")).status, 409, "an accepted ID cannot change execution mode");
    assert.equal((await retry("auto", "different-content")).status, 409);
  } finally {
    await reader?.cancel();
    for (const session of sessions) await session.dispose();
    await store.close();
    delete globalThis.__pioraShellStore;
    assert.ok(path.resolve(directory).startsWith(path.resolve(tmpdir()) + path.sep) && path.basename(directory).startsWith("piora-shell-legacy-"));
    await rm(directory, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
  }
});
