import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, writeFile, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { createRequire } from "node:module";
import { chromium } from "playwright-core";
const require = createRequire(import.meta.url);
const { webpack } = require("next/dist/compiled/webpack/webpack.js");
const repo = path.resolve(import.meta.dirname, "..");

test("terminal history supports keyboard, mouse, reload, project isolation and failed sends", { timeout: 120000 }, async () => {
  const root = await mkdtemp(path.join(tmpdir(), "piora-terminal-history-"));
  let browser;
  try {
    await writeFile(path.join(root, "loader.cjs"), `const ts=require(${JSON.stringify(require.resolve("typescript"))});module.exports=s=>ts.transpileModule(s,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText`);
    await writeFile(path.join(root, "css.cjs"), `module.exports=s=>"export default "+JSON.stringify(Object.fromEntries([...s.matchAll(/\\.([a-zA-Z][\\w-]*)/g)].map(m=>[m[1],m[1]])))`);
    await writeFile(path.join(root, "i18n.ts"), `import {zhCNLocale} from ${JSON.stringify(path.join(repo, "lib/i18n/messages/zh-CN.ts"))};export const useI18n=()=>({t:key=>zhCNLocale.messages[key]??key});`);
    await writeFile(path.join(root, "entry.tsx"), `import React from "react";import {createRoot} from "react-dom/client";import {TerminalCommandInput} from ${JSON.stringify(path.join(repo, "components/workspace/TerminalCommandInput.tsx"))};window.sent=[];function App(){const [cwd,setCwd]=React.useState("C:/Workspace/sample");window.changeProject=setCwd;return <section className="root" style={{height:480,width:"100%",maxWidth:480,margin:"30px auto",borderRadius:10}}><div style={{padding:16}}>终端 · Piora</div><pre style={{flex:1,padding:16,color:"#b3c7d3"}}>Microsoft Windows\nC:\\Workspace\\sample&gt;</pre><TerminalCommandInput key={cwd} cwd={cwd} disabled={false} onRun={async(command)=>{if(window.fail)throw new Error("连接中断");if(window.delay)await new Promise(resolve=>window.finish=resolve);window.sent.push(command);}}/></section>};createRoot(document.getElementById("root")).render(<App/>);`);
    const compiler = webpack({ mode: "development", target: "web", devtool: false, entry: path.join(root, "entry.tsx"), output: { path: root, filename: "bundle.js" }, resolve: { extensions: [".tsx", ".ts", ".js"], modules: [path.join(repo, "node_modules"), "node_modules"], alias: { "@/hooks/useI18n": path.join(root, "i18n.ts"), "@": repo } }, module: { rules: [{ test: /\.tsx?$/, exclude: /node_modules/, use: path.join(root, "loader.cjs") }, { test: /\.css$/, use: path.join(root, "css.cjs") }] } });
    await new Promise((resolve, reject) => compiler.run((error, stats) => compiler.close(() => error || stats.hasErrors() ? reject(error || new Error(stats.toString({ all: false, errors: true }))) : resolve())));
    const bundle = await readFile(path.join(root, "bundle.js"), "utf8");
    const css = (await readFile(path.join(repo, "components/workspace/TerminalPanel.module.css"), "utf8")).replace(/:global\(([^)]+)\)/g, "$1");
    browser = await chromium.launch({ channel: "msedge", headless: true });
    const page = await browser.newPage({ viewport: { width: 600, height: 650 } });
    const errors = []; page.on("pageerror", (error) => errors.push(error.message));
    await page.route("http://terminal-history.test/**", (route) => route.fulfill({ contentType: "text/html", body: `<!doctype html><style>:root{--ui-font-size:14px;--text-sm:12px;--text-xs:11px;--text-base:14px;--font-mono:Consolas,monospace;--radius-control:6px}*{box-sizing:border-box}body{margin:0;background:#0b1016;font:14px system-ui}${css}</style><div id="root"></div>` }));
    const mount = async () => { await page.goto("http://terminal-history.test/"); await page.addScriptTag({ content: bundle }); };
    await mount();
    const input = page.getByRole("combobox");
    await input.fill("git status --short"); await input.press("Enter");
    await page.waitForFunction(() => window.sent.length === 1);
    await input.fill("git diff --stat"); await input.press("Enter");
    await page.waitForFunction(() => window.sent.length === 2);
    await mount();
    await input.fill("git");
    await page.getByRole("option").first().waitFor();
    assert.deepEqual(await page.getByRole("option").locator("code").allTextContents(), ["git diff --stat", "git status --short"]);
    await input.press("ArrowDown"); await input.press("Enter");
    assert.equal(await input.inputValue(), "git diff --stat");
    assert.deepEqual(await page.evaluate(() => window.sent), [], "selection never executes");
    await input.fill("git"); await page.getByRole("option").filter({ hasText: "git status --short" }).click();
    assert.equal(await input.inputValue(), "git status --short");
    assert.deepEqual(await page.evaluate(() => window.sent), []);
    await input.fill("git d"); await input.press("Tab");
    assert.equal(await input.inputValue(), "git diff --stat");
    await input.fill("git"); await input.press("Escape");
    assert.equal(await page.getByRole("option").count(), 0);
    await page.evaluate(() => window.changeProject("F:/Other"));
    await input.fill("git"); assert.equal(await page.getByRole("option").count(), 0);
    await page.evaluate(() => window.changeProject("C:/Workspace/sample"));
    await input.fill("git"); await page.getByRole("option").first().waitFor();
    await page.setViewportSize({ width: 360, height: 650 });
    const bounds = await page.getByRole("listbox").boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 360);
    await mkdir(path.join(repo, ".verification"), { recursive: true });
    await page.screenshot({ path: path.join(repo, ".verification/terminal-history.png") });
    await page.evaluate(() => { window.fail = true; });
    await input.fill("echo failed"); await input.press("Enter");
    await page.getByRole("alert").waitFor(); assert.equal(await input.inputValue(), "echo failed");
    await page.evaluate(() => { window.fail = false; window.delay = true; });
    await input.fill("echo first"); await input.press("Enter");
    await page.waitForFunction(() => Boolean(window.finish));
    await input.fill("echo newer draft"); await page.evaluate(() => window.finish());
    await page.waitForFunction(() => window.sent.length === 1);
    assert.equal(await input.inputValue(), "echo newer draft");
    assert.deepEqual(errors, []);
  } finally { await browser?.close(); await rm(root, { recursive: true, force: true }); }
});
